### ISSUE TITLE
Dear Sir, I would like to report an issue. Sometimes I cannot download picture or videos but other times I can Download them. Please help thank you!

### ISSUE THREAD

**Issue by ashokaramani** [HuiiBuh/InstagramDownloader#319]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
3. See error

**Expected behaviour**

**Screenshots**

**Device (please complete the following information):**
- Resolution: [e.g 2K]
- Browser [e.g. chrome, firefox]
- Extension Version [e.g. 4.0.1]

**Additional context**

**Comment by geek-at-heart** [comment]
Suddenly not showing download button for me as of a day or two ago.

**Comment by skyfox1977** [comment]
I have same issue

**Comment by Simon311** [comment]
Shows the button when you right click and open a separate tab with the post, but on single-image posts it will fail to find the link, which is surprising, considering it's still on the page as a normal img tag.

**Comment by Simon311** [comment]
Also, things often get saved with "unknown" being the author

**Comment by geek-at-heart** [comment]
For other Firefox users impacted by this, I found another extension helpful:
[Double-click Image Downloader](https://addons.mozilla.org/en-US/firefox/addon/double-click-image-download/)
A general plugin for grabbing _any_ images. You might find helpful until this is fixed.

**Comment by AlbertArulPrakash** [comment]
The problem is in this function (bold line). I am also facing this for past couple of weeks

static downloadWithOutSlider(e) {
                return t(this, void 0, void 0, (function*() {
                    const t = e.querySelector(r.POST_CONTENT_WRAPPER)
                      **, n = t.querySelector("img")**
                      , i = t.querySelector("video");
                    yield v.download(n, i, e)
                }
                ))
error message is : TypeError: Cannot read properties of null (reading 'querySelector')

Exception Stack:

extension.js:formatted:5958 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelector')
    at Function.<anonymous> (extension.js:formatted:5958)
    at Generator.next (<anonymous>)
    at extension.js:formatted:5285
    at new Promise (<anonymous>)
    at t (extension.js:formatted:5262)
    at Function.downloadWithOutSlider (extension.js:formatted:5956)
    at Function.<anonymous> (extension.js:formatted:5508)
    at Generator.next (<anonymous>)
    at extension.js:formatted:5285
    at new Promise (<anonymous>)

**Comment by AlbertArulPrakash** [comment]
I noticed this behavior. When a story is having only one Photograph, while clicking the download button is throwing this error. 
If there are more than one photograph, then download function works properly. 
This behavior is not observed for Video media

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelector')
    at v.<anonymous> (extension.js:2:116723)
    at Generator.next (<anonymous>)
    at extension.js:2:100426
    at new Promise (<anonymous>)
    at t (extension.js:2:100171)
    at v.downloadWithOutSlider (extension.js:2:116637)
    at v.<anonymous> (extension.js:2:105254)
    at Generator.next (<anonymous>)
    at extension.js:2:100426
    at new Promise (<anonymous>)
