### ISSUE TITLE
Bulk Download not functioning

### ISSUE THREAD

**Issue by Chloeana** [HuiiBuh/InstagramDownloader#352]
# Bulk Download not funcitoning

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
2. Click on 'Download All'
3. Page refreshes. Download does not start.

**Expected behaviour**
Download Starts

**Screenshots**
![image](https://github.com/igdownloader/InstagramDownloader/assets/135464448/284e7638-0266-46c3-9f16-2483047664c5)

**Device (please complete the following information):**
- Resolution: 2K
- Browser: Chrome
- Extension Version: 4.8.4

**Additional context**
Error message in Chrome console: 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'user')
    at y.<anonymous> (BulkPostDownloader.ts:95:26)
    at Generator.next (<anonymous>)
    at i (tslib.es6.js:73:58)

**Comment by amuagarwal** [comment]
check for chrome://flags or brave://flags and cross check for "File System Access API" is enabled
